routes:
  # EXAMPLE ROUTE
  iron_to_diamond:
    # Name of the route
    display-name: "Iron → Diamond Run"
    npc-id: 4378973456
    waypoint-world: "world"

    # Movement
    speed: 1.15                 # Citizens speedModifier (1.0 = normal)
    follow-radius: 24           # Max. Distance Owner ↔ NPC before the NPC stops moving
    expire-seconds: 900         # The time after which the route will forcefully end and return the initial invested items

    announce-start: true        # Whether to announce the start of a route in the global chat
    trade-delay-seconds: 8      # For how long the NPC will stop at the destination before returning back (won't return back if no coordinates follow after the "trade" step)

    # Steps/Waypoints that the NPC will walk
    steps:
      - { x: 100.5, y: 64.0, z: -30.5 }   # Start/Spawn & Home-Pos
      - { x: 120.5, y: 64.0, z: -30.5 }
      - trade
      - { x: 140.5, y: 64.0, z: -15.5 }    # Last Waypoint = End & Claim-Spot

    # Trade definition
    trades:
      - input:  { material: IRON_INGOT, amount: 20 }
        output: { material: DIAMOND,    amount: 10 }

    daily-limit: 3
    cooldown-seconds: 3600
